// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  {
    checkpoint: () => "Checkpoint";
    "checkpoint-helper-text": () => "Stop students from going backwards";
    end: () => "End";
    "end-helper-text": () => "The last node in your flow";
    "node-finished": () => "Finished";
    "node-skipped": () => "Skipped";
    "node-started": () => "Started";
    start: () => "Start";
    "start-helper-text": () => "The first node in your flow";
    synchronize: () => "Synchronize";
    "synchronize-helper-text": () => "Force students to wait on your signal";
  }
>({
  "en-GB": createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-helper-text": "Stop students from going backwards",
    end: "End",
    "end-helper-text": "The last node in your flow",
    "node-finished": "Finished",
    "node-skipped": "Skipped",
    "node-started": "Started",
    start: "Start",
    "start-helper-text": "The first node in your flow",
    synchronize: "Synchronize",
    "synchronize-helper-text": "Force students to wait on your signal",
  }),
  en: createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-helper-text": "Stop students from going backwards",
    end: "End",
    "end-helper-text": "The last node in your flow",
    "node-finished": "Finished",
    "node-skipped": "Skipped",
    "node-started": "Started",
    start: "Start",
    "start-helper-text": "The first node in your flow",
    synchronize: "Synchronize",
    "synchronize-helper-text": "Force students to wait on your signal",
  }),
  "en-US": createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-helper-text": "Stop students from going backwards",
    end: "End",
    "end-helper-text": "The last node in your flow",
    "node-finished": "Finished",
    "node-skipped": "Skipped",
    "node-started": "Started",
    start: "Start",
    "start-helper-text": "The first node in your flow",
    synchronize: "Synchronize",
    "synchronize-helper-text": "Force students to wait on your signal",
  }),
  de: createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-helper-text": "Stop students from going backwards",
    end: "End",
    "end-helper-text": "The last node in your flow",
    "node-finished": "Finished",
    "node-skipped": "Skipped",
    "node-started": "Started",
    start: "Start",
    "start-helper-text": "The first node in your flow",
    synchronize: "Synchronize",
    "synchronize-helper-text": "Force students to wait on your signal",
  }),
});

export default translations;
