/**
 * Turns MathLive's font stylesheet into one with the fonts inside it.
 *
 * MathLive ships `mathlive-fonts.css` next to a `fonts/` directory and fetches
 * the twenty woff2 files at runtime from wherever `MathfieldElement.fontsDirectory`
 * points. That is exactly the separate asset a consumer has to remember to
 * deploy, and the convention here is that a bit brings everything it needs —
 * `injectStyles` puts the CSS in the JS for the same reason.
 *
 * So: read their stylesheet, replace every `url(fonts/X.woff2)` with a data
 * URI, and write it where the bundle can `?inline` it. The `--ML__static-fonts`
 * flag their stylesheet already sets is what tells MathLive the fonts are
 * accounted for and it need not go looking.
 *
 * Run from `build`. The output is generated, not edited.
 */
import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const require = createRequire(import.meta.url);
// `fonts.css` is an exported subpath and `package.json` is not, so this is the
// supported way to find where MathLive was installed.
const source = require.resolve("mathlive/fonts.css");
const mathlive = dirname(source);
const target = resolve(import.meta.dirname, "..", "src", "generated", "fonts.css");

const css = await readFile(source, "utf8");

let embedded = 0;
let bytes = 0;

const inlined = await replaceAsync(css, /url\(fonts\/([\w-]+\.woff2)\)/g, async (_match, file) => {
  const font = await readFile(join(mathlive, "fonts", file));
  embedded += 1;
  bytes += font.length;
  return `url(data:font/woff2;base64,${font.toString("base64")})`;
});

if (embedded === 0) {
  // A silent zero here would ship a stylesheet pointing at files that are not
  // there, and the maths would render in whatever serif the browser has.
  throw new Error(`No fonts found to embed in ${source}. Has MathLive changed its layout?`);
}

// The directory is not committed either — nothing in it is.
await mkdir(dirname(target), { recursive: true });

await writeFile(
  target,
  `/* Generated by scripts/inlineFonts.mjs from MathLive's mathlive-fonts.css.\n` +
    `   Do not edit: run \`pnpm --filter @bitflow/task-math prepare-fonts\`.\n` +
    `   ${embedded} fonts, ${Math.round(bytes / 1024)} kB before base64. */\n` +
    inlined +
    "\n",
);

console.log(
  `Embedded ${embedded} fonts (${Math.round(bytes / 1024)} kB) into ${target}`,
);

/** `String.replace` with an async replacer, which JS still does not have. */
async function replaceAsync(input, pattern, replacer) {
  const replacements = [];
  input.replace(pattern, (...args) => {
    replacements.push(replacer(...args));
    return "";
  });
  const resolved = await Promise.all(replacements);
  return input.replace(pattern, () => resolved.shift());
}
