// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en" | "de",
  {
    bitflow: () => "Bitflow";
    "bitflow-description": () =>
      | "A library for creating and conducting dynamic flow-based assessments."
      | "Eine Bibliothek zum Erstellen und Durchführen von dynamischen flow-basierten Assessments.";
    contact: () => "Contact";
    "convert-flow-json-to-string": () => "Convert JSON to String";
    "convert-flow-string-to-json": () => "Convert String to JSON";
    converter: () => "Converter";
    "demo-flows": () => "Demo Flows";
    "do-flow": () => "Do";
    documentation: () => "Documentation";
    download: () => "Download";
    "edit-flow": () => "Edit";
    editor: () => "Editor";
    "flow-json": () => "Flow JSON";
    "flow-string": () => "Flow String";
    "getting-started": () => "Getting Started";
    "my-flows": () => "My Flows";
    preview: () => "Preview";
    save: () => "Save";
    share: () => "Share";
  }
>({
  en: createLanguage({
    bitflow: "Bitflow",
    "bitflow-description":
      "A library for creating and conducting dynamic flow-based assessments.",
    contact: "Contact",
    "convert-flow-json-to-string": "Convert JSON to String",
    "convert-flow-string-to-json": "Convert String to JSON",
    converter: "Converter",
    "demo-flows": "Demo Flows",
    "do-flow": "Do",
    documentation: "Documentation",
    download: "Download",
    "edit-flow": "Edit",
    editor: "Editor",
    "flow-json": "Flow JSON",
    "flow-string": "Flow String",
    "getting-started": "Getting Started",
    "my-flows": "My Flows",
    preview: "Preview",
    save: "Save",
    share: "Share",
  }),
  de: createLanguage({
    bitflow: "Bitflow",
    "bitflow-description":
      "Eine Bibliothek zum Erstellen und Durchführen von dynamischen flow-basierten Assessments.",
    contact: "Contact",
    "convert-flow-json-to-string": "Convert JSON to String",
    "convert-flow-string-to-json": "Convert String to JSON",
    converter: "Converter",
    "demo-flows": "Demo Flows",
    "do-flow": "Do",
    documentation: "Documentation",
    download: "Download",
    "edit-flow": "Edit",
    editor: "Editor",
    "flow-json": "Flow JSON",
    "flow-string": "Flow String",
    "getting-started": "Getting Started",
    "my-flows": "My Flows",
    preview: "Preview",
    save: "Save",
    share: "Share",
  }),
});

export default translations;
