// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  { description: () => " "; markdown: () => "Markdown"; name: () => "Markdown" }
>({
  "en-GB": createLanguage({
    description: " ",
    markdown: "Markdown",
    name: "Markdown",
  }),
  en: createLanguage({
    description: " ",
    markdown: "Markdown",
    name: "Markdown",
  }),
  "en-US": createLanguage({
    description: " ",
    markdown: "Markdown",
    name: "Markdown",
  }),
  de: createLanguage({
    description: " ",
    markdown: "Markdown",
    name: "Markdown",
  }),
});

export default translations;
