// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  {
    checkpoint: () => "Checkpoint";
    "checkpoint-text": () => "You reached a checkpoint and can not go back to a previous task.";
    continue: () => "Continue";
    input: () => "Input";
    next: () => "Next";
    refresh: () => "Refresh";
    synchronize: () => "Synchronize";
    "synchronize-text": () => "Wait until the next node is unlocked.";
    task: () => "Task";
    title: () => "Title";
  }
>({
  "en-GB": createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-text":
      "You reached a checkpoint and can not go back to a previous task.",
    continue: "Continue",
    input: "Input",
    next: "Next",
    refresh: "Refresh",
    synchronize: "Synchronize",
    "synchronize-text": "Wait until the next node is unlocked.",
    task: "Task",
    title: "Title",
  }),
  en: createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-text":
      "You reached a checkpoint and can not go back to a previous task.",
    continue: "Continue",
    input: "Input",
    next: "Next",
    refresh: "Refresh",
    synchronize: "Synchronize",
    "synchronize-text": "Wait until the next node is unlocked.",
    task: "Task",
    title: "Title",
  }),
  "en-US": createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-text":
      "You reached a checkpoint and can not go back to a previous task.",
    continue: "Continue",
    input: "Input",
    next: "Next",
    refresh: "Refresh",
    synchronize: "Synchronize",
    "synchronize-text": "Wait until the next node is unlocked.",
    task: "Task",
    title: "Title",
  }),
  de: createLanguage({
    checkpoint: "Checkpoint",
    "checkpoint-text":
      "You reached a checkpoint and can not go back to a previous task.",
    continue: "Continue",
    input: "Input",
    next: "Next",
    refresh: "Refresh",
    synchronize: "Synchronize",
    "synchronize-text": "Wait until the next node is unlocked.",
    task: "Task",
    title: "Title",
  }),
});

export default translations;
