/**
 * Turns KaTeX's stylesheet into one with its fonts inside it.
 *
 * `katex.min.css` points each `@font-face` at three files in a `fonts/`
 * directory beside it — woff2, woff and ttf. That directory is the separate
 * asset a consumer would have to remember to deploy, and the convention here is
 * that the bundle brings everything it needs (see `injectStyles`).
 *
 * So: keep only the woff2 source of each face, which every browser bitflow
 * runs in reads, replace it with a data URI, and write the result where the
 * lazily loaded maths chunk can `?inline` it. The woff and ttf fallbacks would
 * triple the size for browsers that are not in the support matrix.
 *
 * Run from `build`. The output is generated, not edited.
 */
import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const require = createRequire(import.meta.url);
// The stylesheet is not an exported subpath, but the entry point is, and the
// stylesheet sits next to it in `dist/`.
const katex = dirname(require.resolve("katex"));
const source = join(katex, "katex.min.css");
const target = resolve(import.meta.dirname, "..", "src", "generated", "katex.css");

const css = await readFile(source, "utf8");

let embedded = 0;
let bytes = 0;

const inlined = await replaceAsync(
  css,
  /src:url\(fonts\/([\w-]+\.woff2)\) format\("woff2"\)[^;}]*/g,
  async (_match, file) => {
    const font = await readFile(join(katex, "fonts", file));
    embedded += 1;
    bytes += font.length;
    return `src:url(data:font/woff2;base64,${font.toString("base64")}) format("woff2")`;
  },
);

if (embedded === 0) {
  // A silent zero here would ship a stylesheet pointing at files that are not
  // there, and the maths would render in whatever serif the browser has.
  throw new Error(`No fonts found to embed in ${source}. Has KaTeX changed its layout?`);
}
if (inlined.includes("url(fonts/")) {
  throw new Error(`${source} still points at fonts/ after inlining. Has KaTeX changed its layout?`);
}

// The directory is not committed either — nothing in it is.
await mkdir(dirname(target), { recursive: true });

await writeFile(
  target,
  `/* Generated by scripts/inlineKatexFonts.mjs from KaTeX's katex.min.css.\n` +
    `   Do not edit: run \`pnpm --filter @bitflow/element prepare-fonts\`.\n` +
    `   ${embedded} fonts, ${Math.round(bytes / 1024)} kB before base64. */\n` +
    inlined +
    "\n",
);

console.log(`Embedded ${embedded} fonts (${Math.round(bytes / 1024)} kB) into ${target}`);

/** `String.replace` with an async replacer, which JS still does not have. */
async function replaceAsync(input, pattern, replacer) {
  const replacements = [];
  input.replace(pattern, (...args) => {
    replacements.push(replacer(...args));
    return "";
  });
  const resolved = await Promise.all(replacements);
  return input.replace(pattern, () => resolved.shift());
}
