// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en" | "de",
  { markdown: () => "Markdown" }
>({
  en: createLanguage({ markdown: "Markdown" }),
  de: createLanguage({ markdown: "Markdown" }),
});

export default translations;
