// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  { markdown: () => "Markdown" }
>({
  "en-GB": createLanguage({ markdown: "Markdown" }),
  en: createLanguage({ markdown: "Markdown" }),
  "en-US": createLanguage({ markdown: "Markdown" }),
  de: createLanguage({ markdown: "Markdown" }),
});

export default translations;
