// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de" | "fr" | "es" | "nl" | "pt" | "tr",
  {
    "add-pattern": () => "Add Pattern";
    "delete-pattern": () => "Delete";
    description: () => "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.";
    error: () => "Error";
    info: () => "Info";
    inputs: () => "Inputs";
    "statistic-inputs-description": () => "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.";
    instruction: () => "Instruction";
    message: () => "Message";
    name: () => "Input";
    pattern: () => "Pattern";
    "pattern-error-duplicate": () => "A pattern can not contain duplicates";
    "pattern-error-exists": () => "This pattern already exists";
    "pattern-error-invalid": () => "Not a valid pattern";
    "pattern-regex": () => "You can input a RegEx";
    "pattern-title": (values: { pattern: string }) => string;
    patterns: () => "Patterns";
    "statistic-patterns-description": () => "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.";
    severity: () => "Severity";
    success: () => "Success";
    up: () => "Up";
    warning: () => "Warning";
  }
>({
  "en-GB": createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  en: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  "en-US": createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  de: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  fr: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  es: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  nl: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  pt: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  tr: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    description:
      "A task bit for creating single line response questions. The answer of a user can be automatically evaluated by providing a regular expression. You can also give feedback by using regular expression, as well.",
    error: "Error",
    info: "Info",
    inputs: "Inputs",
    "statistic-inputs-description":
      "Here you can see the frequency of all answers represented in a cloud. Hovering over an answer will show you the frequency. Green highlighted answers are correct ones.",
    instruction: "Instruction",
    message: "Message",
    name: "Input",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    "statistic-patterns-description":
      "Here you can see the frequency of the found feedback and evaluation patterns. Green highlighted patterns are correct ones, which match the evaluation pattern.",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
});

export default translations;
