// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en" | "de",
  {
    "add-pattern": () => "Add Pattern";
    "delete-pattern": () => "Delete";
    error: () => "Error";
    info: () => "Info";
    instruction: () => "Instruction";
    message: () => "Message";
    pattern: () => "Pattern";
    "pattern-error-duplicate": () => "A pattern can not contain duplicates";
    "pattern-error-exists": () => "This pattern already exists";
    "pattern-error-invalid": () => "Not a valid pattern";
    "pattern-regex": () => "You can input a RegEx";
    "pattern-title": (values: { pattern: string }) => string;
    patterns: () => "Patterns";
    severity: () => "Severity";
    success: () => "Success";
    up: () => "Up";
    warning: () => "Warning";
  }
>({
  en: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    error: "Error",
    info: "Info",
    instruction: "Instruction",
    message: "Message",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
  de: createLanguage({
    "add-pattern": "Add Pattern",
    "delete-pattern": "Delete",
    error: "Error",
    info: "Info",
    instruction: "Instruction",
    message: "Message",
    pattern: "Pattern",
    "pattern-error-duplicate": "A pattern can not contain duplicates",
    "pattern-error-exists": "This pattern already exists",
    "pattern-error-invalid": "Not a valid pattern",
    "pattern-regex": "You can input a RegEx",
    "pattern-title": "Pattern {pattern}",
    patterns: "Patterns",
    severity: "Severity",
    success: "Success",
    up: "Up",
    warning: "Warning",
  }),
});

export default translations;
