/**
 * A minimal reader for PBM's plain "P1" format: the "ASCII bitmap" the school
 * book prints as a listing of 0s and 1s. Pure and deliberately narrow — no
 * PGM, no PPM, no binary "P4" — because the one thing an author pastes here is
 * text copied straight out of the book or generated by hand, and the default
 * black-and-white palette is exactly what a PBM listing means: 1 is black
 * ("foreground"), 0 is white.
 *
 * A `#` starts a comment that runs to the end of its line, exactly as the
 * format specifies, so a listing copied with its comments intact still reads.
 */
export type ParsedPbm = {
  rows: number;
  columns: number;
  /** Palette ids from `DEFAULT_PALETTE`: "white" or "black" per cell. */
  cells: string[][];
};

/**
 * Why a listing could not be read, as a key into `formMessages` and the values
 * it needs — the form is in the author's language, so the parser only says
 * which problem it was.
 */
export class PbmError extends Error {
  constructor(
    readonly key: string,
    readonly vars: Record<string, string | number> = {},
  ) {
    super(key);
  }
}

export const parsePbm = (text: string): ParsedPbm => {
  const tokens = text
    .split("\n")
    .map((line) => line.replace(/#.*/, ""))
    .join("\n")
    .split(/\s+/)
    .filter((token) => token.length > 0);

  if (tokens[0] !== "P1") {
    throw new PbmError("pbmNoMagic");
  }

  const columns = Number(tokens[1]);
  const rows = Number(tokens[2]);
  if (!Number.isInteger(columns) || !Number.isInteger(rows) || columns <= 0 || rows <= 0) {
    throw new PbmError("pbmBadSize");
  }

  // The format allows the pixels to run together without whitespace — "01110"
  // is five pixels, not one token — so what follows the header is read a
  // character at a time.
  const bits = tokens.slice(3).join("").split("");
  if (bits.length !== rows * columns) {
    throw new PbmError("pbmCount", {
      expected: rows * columns,
      rows,
      columns,
      found: bits.length,
    });
  }

  const cells: string[][] = [];
  for (let row = 0; row < rows; row++) {
    const line: string[] = [];
    for (let column = 0; column < columns; column++) {
      const bit = bits[row * columns + column];
      if (bit !== "0" && bit !== "1") {
        throw new PbmError("pbmBadValue", { value: bit });
      }
      line.push(bit === "1" ? "black" : "white");
    }
    cells.push(line);
  }

  return { rows, columns, cells };
};
