// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de" | "fr" | "es" | "nl" | "pt" | "tr",
  {}
>({
  "en-GB": createLanguage({}),
  en: createLanguage({}),
  "en-US": createLanguage({}),
  de: createLanguage({}),
  fr: createLanguage({}),
  es: createLanguage({}),
  nl: createLanguage({}),
  pt: createLanguage({}),
  tr: createLanguage({}),
});

export default translations;
