// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de" | "fr" | "es" | "nl" | "pt" | "tr",
  { "number-of-persons": () => "Number of persons" }
>({
  "en-GB": createLanguage({ "number-of-persons": "Number of persons" }),
  en: createLanguage({ "number-of-persons": "Number of persons" }),
  "en-US": createLanguage({ "number-of-persons": "Number of persons" }),
  de: createLanguage({ "number-of-persons": "Number of persons" }),
  fr: createLanguage({ "number-of-persons": "Number of persons" }),
  es: createLanguage({ "number-of-persons": "Number of persons" }),
  nl: createLanguage({ "number-of-persons": "Number of persons" }),
  pt: createLanguage({ "number-of-persons": "Number of persons" }),
  tr: createLanguage({ "number-of-persons": "Number of persons" }),
});

export default translations;
