// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  {
    description: () => " ";
    "example.markdown": () => "This is an example. Feel free to use it as a template.";
    "example.title": () => "Welcome";
    markdown: () => "Markdown";
    name: () => "Simple";
    title: () => "Title";
  }
>({
  "en-GB": createLanguage({
    description: " ",
    "example.markdown":
      "This is an example. Feel free to use it as a template.",
    "example.title": "Welcome",
    markdown: "Markdown",
    name: "Simple",
    title: "Title",
  }),
  en: createLanguage({
    description: " ",
    "example.markdown":
      "This is an example. Feel free to use it as a template.",
    "example.title": "Welcome",
    markdown: "Markdown",
    name: "Simple",
    title: "Title",
  }),
  "en-US": createLanguage({
    description: " ",
    "example.markdown":
      "This is an example. Feel free to use it as a template.",
    "example.title": "Welcome",
    markdown: "Markdown",
    name: "Simple",
    title: "Title",
  }),
  de: createLanguage({
    description: " ",
    "example.markdown":
      "This is an example. Feel free to use it as a template.",
    "example.title": "Welcome",
    markdown: "Markdown",
    name: "Simple",
    title: "Title",
  }),
});

export default translations;
