// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de" | "fr" | "es" | "nl" | "pt" | "tr",
  {
    description: () => " ";
    "example.feedback.no": () => "No is not correct" | "Nein ist nicht korrekt";
    "example.feedback.yes": () => "Yes is correct" | "Ja ist korrekt";
    name: () => "Yes No" | "Ja Nein";
    no: () => "No" | "Nein";
    question: () => "Question" | "Frage";
    "severity.error": () => "Error" | "Fehler";
    "severity.info": () => "Info";
    "severity.success": () => "Success" | "Erfolgreich";
    "severity.warning": () => "Warning" | "Warnung";
    yes: () => "Yes" | "Ja";
  }
>({
  "en-GB": createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  en: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  "en-US": createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  de: createLanguage({
    description: " ",
    "example.feedback.no": "Nein ist nicht korrekt",
    "example.feedback.yes": "Ja ist korrekt",
    name: "Ja Nein",
    no: "Nein",
    question: "Frage",
    "severity.error": "Fehler",
    "severity.info": "Info",
    "severity.success": "Erfolgreich",
    "severity.warning": "Warnung",
    yes: "Ja",
  }),
  fr: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  es: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  nl: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  pt: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
  tr: createLanguage({
    description: " ",
    "example.feedback.no": "No is not correct",
    "example.feedback.yes": "Yes is correct",
    name: "Yes No",
    no: "No",
    question: "Question",
    "severity.error": "Error",
    "severity.info": "Info",
    "severity.success": "Success",
    "severity.warning": "Warning",
    yes: "Yes",
  }),
});

export default translations;
