// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de",
  {
    accept: () => "Accept" | "Akzeptieren";
    answer: () => "Answer" | "Antworten";
    close: () => "Close" | "Schließen";
    confidence: () => "Confidence";
    correctNudges: (values: { index: number }) => string;
    end: () => "End";
    manualNudges: (values: { index: number }) => string;
    next: () => "Next" | "Weiter";
    previous: () => "Previous" | "Zurück";
    reasoning: () => "Reasoning" | "Begründung";
    retry: () => "Retry" | "Erneut versuchen";
    skip: () => "Skip" | "Überspringen";
    start: () => "Start";
    unknownNudges: (values: { index: number }) => string;
    wrongNudges: (values: { index: number }) => string;
  }
>({
  "en-GB": createLanguage({
    accept: "Accept",
    answer: "Answer",
    close: "Close",
    confidence: "Confidence",
    correctNudges:
      "{index, plural, =0 {Nice one!} =1 {Great!} other {Keep it going!}}",
    end: "End",
    manualNudges:
      "{index, plural, other {Your answer will be check manually!}}",
    next: "Next",
    previous: "Previous",
    reasoning: "Reasoning",
    retry: "Retry",
    skip: "Skip",
    start: "Start",
    unknownNudges:
      "{index, plural, =0 {Thanks for your answer!} other {Thank you for answering!}}",
    wrongNudges:
      "{index, plural, =0 {Maybe next time} =1 {No worries!} other {Every wrong answer is a learning opportunity!}}",
  }),
  en: createLanguage({
    accept: "Accept",
    answer: "Answer",
    close: "Close",
    confidence: "Confidence",
    correctNudges:
      "{index, plural, =0 {Nice one!} =1 {Great!} other {Keep it going!}}",
    end: "End",
    manualNudges:
      "{index, plural, other {Your answer will be check manually!}}",
    next: "Next",
    previous: "Previous",
    reasoning: "Reasoning",
    retry: "Retry",
    skip: "Skip",
    start: "Start",
    unknownNudges:
      "{index, plural, =0 {Thanks for your answer!} other {Thank you for answering!}}",
    wrongNudges:
      "{index, plural, =0 {Maybe next time} =1 {No worries!} other {Every wrong answer is a learning opportunity!}}",
  }),
  "en-US": createLanguage({
    accept: "Accept",
    answer: "Answer",
    close: "Close",
    confidence: "Confidence",
    correctNudges:
      "{index, plural, =0 {Nice one!} =1 {Great!} other {Keep it going!}}",
    end: "End",
    manualNudges:
      "{index, plural, other {Your answer will be check manually!}}",
    next: "Next",
    previous: "Previous",
    reasoning: "Reasoning",
    retry: "Retry",
    skip: "Skip",
    start: "Start",
    unknownNudges:
      "{index, plural, =0 {Thanks for your answer!} other {Thank you for answering!}}",
    wrongNudges:
      "{index, plural, =0 {Maybe next time} =1 {No worries!} other {Every wrong answer is a learning opportunity!}}",
  }),
  de: createLanguage({
    accept: "Akzeptieren",
    answer: "Antworten",
    close: "Schließen",
    confidence: "Confidence",
    correctNudges:
      "{index, plural, =0 {Sehr gut!} =1 {Super!} other {Weiter so!}}",
    end: "End",
    manualNudges:
      "{index, plural, other {Deine Antwort wird manuell überprüft!}}",
    next: "Weiter",
    previous: "Zurück",
    reasoning: "Begründung",
    retry: "Erneut versuchen",
    skip: "Überspringen",
    start: "Start",
    unknownNudges:
      "{index, plural, =0 {Danke für deine Antwort!} other {Danke!}}",
    wrongNudges:
      "{index, plural, =0 {Vielleicht nächstes Mal} =1 {Keine Sorge!} other {Jede falsche Antwort ist eine Chance was zu lernen!}}",
  }),
});

export default translations;
