// This file is automatically generated by Vocab.
// To make changes update translation.json files directly.

import { createLanguage, createTranslationFile } from "@vocab/core/runtime";

const translations = createTranslationFile<
  "en-GB" | "en" | "en-US" | "de" | "fr" | "es" | "nl" | "pt" | "tr",
  {
    description: () => " ";
    example: () => "Example" | "Beispiel";
    name: () => "Do Local";
  }
>({
  "en-GB": createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  en: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  "en-US": createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  de: createLanguage({
    description: " ",
    example: "Beispiel",
    name: "Do Local",
  }),
  fr: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  es: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  nl: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  pt: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
  tr: createLanguage({
    description: " ",
    example: "Example",
    name: "Do Local",
  }),
});

export default translations;
